# Generated by Django 2.2.7 on 2019-11-30 17:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
            ],
        ),
        migrations.CreateModel(
            name='Repeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(max_length=15)),
                ('analyte', models.CharField(max_length=50)),
                ('comment', models.CharField(blank=True, max_length=50, null=True)),
                ('entered_by', models.CharField(blank=True, max_length=20, null=True)),
                ('row_position', models.IntegerField(default=0)),
                ('repeat_date', models.DateField(blank=True, default=None, null=True)),
                ('remark', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch_template', models.CharField(blank=True, max_length=50, null=True)),
                ('disabled', models.BooleanField(default=False)),
                ('file_name', models.CharField(blank=True, default='', max_length=90, null=True)),
                ('deactivation_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('archivum_file', models.CharField(blank=True, default='', max_length=90, null=True)),
                ('translated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('inventory_check', models.BooleanField(default=False)),
                ('laboratory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockyard.Laboratory')),
            ],
        ),
    ]
